### ISSUE TITLE
Accounts Tab Not Refreshing Properly.

### ISSUE THREAD

**Issue by AzizulHaque** [nohorjo/Centsa#91]
Sometimes when you click on your accounts, the following shows instead of the accounts. To show the accounts, you have to click on something else and then click back on it and then it loads.
![account balance issue](https://user-images.githubusercontent.com/32259720/37326600-c8a7c070-268a-11e8-910f-f3d7e4d6c801.PNG)

**Comment by nohorjo** [comment]
This is probably due to a network or db issue (as there is a connection limit).
You should show include the output from the dev console (CTRL-SHIFT-i) and the network panel.
Created #93 to provide error messages.

**Comment by nohorjo** [comment]
Added client side error messages (for server errors). Now if there are network or db errors you'll get an alert.  
@AzizulHaque __Please include any error messages you get__
